name: Approval check
on:
  pull_request_review:
    types: [submitted]
    branches:
     - 'releases'
 
jobs:
  approved:
    if: github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'releases'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"
